version: 1.0.0

services:
    web:
      container_name: portfolio_site_project
      build: 
        context: .
        dockerfile: Dockerfile
      ports:
        - "80:80"
      restart: always
      command: nginx -g "daemon off;"
      volumes:
        - ./assets/:/usr/share/nginx/html:ro
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
